###
POST http://localhost:4000/post/create
Content-Type: application/json

{
    "username":"username",
    "content":"test"

}

###
GET https://sheep.up.railway.app/post/newer
###
GET http://localhost:4000/post/newer?latestId=18
####
GET https://sheep.up.railway.app/post/

###
PUT http://localhost:4000/post/1
Content-Type: application/json

{
    "content" :"변경된 게시물"
}

###
DELETE http://localhost:4000/post/2